### ISSUE TITLE
Error in roots watch when using roots-wordpress

### ISSUE THREAD

**Issue by JamieBradders** [carrot/roots-wordpress#6]
Hi there, 

Been trying out the roots-wordpress plugin today and noticed an issue. I have been following the 'Wordpress and Roots' screencast from the roots.cx site and I have found that when linking up my website to the extension, updating the view to iterate through each post and then run roots watch I am getting the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
  at errnoException (net.js:904:11)
  at Server._listen2 (net.js:1042:14)
  at listen (net.js:1064:10)
  at Server.listen (net.js:1138:5)
  at Function.start (/usr/local/lib/node_modules/roots/node_modules/charge/lib/index.js:111:43)
  at Server.start (/usr/local/lib/node_modules/roots/lib/local_server.js:56:32)
  at Compile.<anonymous> (/usr/local/lib/node_modules/roots/lib/cli/watch.js:57:24)
  at tryCatchReject (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:27:9)
  at process._tickCallback (node.js:419:13)

The page does update, I am seeing the correct content from WordPress but of course this error causes the watcher to pack in which means I have to re run the command every time I update a view etc which is a bit of a pain. As far as I can tell, I've not deviated away from the video so I imagine everything should work as per the screencasts.

I was just wondering if anyone else had come across this issue before and if so is there something missing from the video or is it an issue with the extension?

Cheers!

**Comment by jescalan** [comment]
This means you have another roots project running in another terminal tab. `EADDRINUSE` is short for "Error, address in use".

**Comment by JamieBradders** [comment]
Thanks Jeff, sorry for the silly ticket - still getting to grips with it - so far it's awesome though :)
